CREATE TABLE CONTACT (
  id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(150),
  address VARCHAR(150)
);

CREATE TABLE PHONE (
  contactId INTEGER NOT NULL, FOREIGN KEY (contactId) REFERENCES CONTACT(id),
  phone VARCHAR(50)
);

CREATE TABLE FAX (
  contactId INTEGER NOT NULL, FOREIGN KEY (contactId) REFERENCES CONTACT(id),
  fax VARCHAR(50)
);

CREATE TABLE EMAIL (
  contactId INTEGER NOT NULL, FOREIGN KEY (contactId) REFERENCES CONTACT(id),
  email VARCHAR(150)
);

CREATE TABLE OTHER_CONTACT (
  contactId INTEGER NOT NULL, FOREIGN KEY (contactId) REFERENCES CONTACT(id),
  contactType VARCHAR(150),
  contact VARCHAR(150)
);

CREATE TABLE GROUP_ID (
  contactId INTEGER NOT NULL, FOREIGN KEY (contactId) REFERENCES CONTACT(id),
  groupId INTEGER
);
